name: Deploy to Timeweb Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via rsync
        # ИСПРАВЛЕННАЯ ВЕРСИЯ С ТОЧНЫМ ТЕГОМ
        uses: appleboy/rsync-deploy@v1.0.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: ${{ secrets.REMOTE_PATH }}
          flags: "-avz --delete"
