name: Trigger Deploy on Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and run git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          # ВАЖНО: подключаемся как root, т.к. репозиторий принадлежит ему
          username: "root" 
          # ВАЖНО: используем ключ, который дает доступ к нашему серверу
          key: ${{ secrets.SERVER_SSH_KEY_FOR_ANSIBLE }}
          script: |
            cd /var/www/noeon.ru/html
            git pull
