name: Deploy to Timeweb Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files to server
        # Используем rsync-экшен для полной синхронизации
        uses: easingthemes/rsync-deployments-action@v3
        with:
          # Приватный ключ из секретов GitHub
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # Адрес вашего сервера
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          # Пользователь на сервере
          REMOTE_USER: ${{ secrets.SERVER_USER }}

          # ИСТОЧНИК: все файлы в репозитории
          SOURCE: "./"
          # ЦЕЛЬ: папка сайта на сервере
          TARGET: ${{ secrets.REMOTE_PATH }}
          # АРГУМЕНТЫ: включая --delete для очистки от мусора
          ARGS: "-avz --delete"
