name: Deploy to Timeweb Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # ИЗМЕНЕНИЕ ЗДЕСЬ: УКАЗЫВАЕМ КОНКРЕТНЫЙ ФАЙЛ
          source: "index.html"
          target: ${{ secrets.REMOTE_PATH }}
